import type { InventoryItem, DashboardStats, AuditHistory, User } from '../types';

export const mockUser: User = {
  username: 'demo.user@company.com',
  roles: {
    isServiceDesk: true,
    isReadOnly: false,
    isAdmin: true,
  },
};

export const mockInventoryItems: InventoryItem[] = [
  {
    id: 1,
    itemNumber: 'LT-001',
    hardwareDescription: 'Dell Latitude 5420 Laptop',
    hardwareType: 'Laptop',
    cost: 1299.99,
    minimumThreshold: 10,
    reorderAmount: 20,
    currentQuantity: 8,
    lastModifiedBy: 'john.doe@company.com',
    lastModifiedDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    needsReorder: true,
  },
  {
    id: 2,
    itemNumber: 'KB-002',
    hardwareDescription: 'Logitech MX Keys Wireless Keyboard',
    hardwareType: 'Keyboard',
    cost: 99.99,
    minimumThreshold: 15,
    reorderAmount: 30,
    currentQuantity: 45,
    lastModifiedBy: 'sarah.smith@company.com',
    lastModifiedDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    needsReorder: false,
  },
  {
    id: 3,
    itemNumber: 'MS-003',
    hardwareDescription: 'Logitech MX Master 3 Mouse',
    hardwareType: 'Mouse',
    cost: 79.99,
    minimumThreshold: 20,
    reorderAmount: 40,
    currentQuantity: 12,
    lastModifiedBy: 'mike.johnson@company.com',
    lastModifiedDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    needsReorder: true,
  },
  {
    id: 4,
    itemNumber: 'MON-004',
    hardwareDescription: 'Dell 27" UltraSharp Monitor U2722DE',
    hardwareType: 'Monitor',
    cost: 549.99,
    minimumThreshold: 8,
    reorderAmount: 15,
    currentQuantity: 25,
    lastModifiedBy: 'emily.davis@company.com',
    lastModifiedDate: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    needsReorder: false,
  },
  {
    id: 5,
    itemNumber: 'DK-005',
    hardwareDescription: 'Dell Docking Station WD19TB',
    hardwareType: 'Docking Station',
    cost: 299.99,
    minimumThreshold: 12,
    reorderAmount: 25,
    currentQuantity: 18,
    lastModifiedBy: 'alex.brown@company.com',
    lastModifiedDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    needsReorder: false,
  },
  {
    id: 6,
    itemNumber: 'HD-006',
    hardwareDescription: 'Jabra Evolve2 65 Headset',
    hardwareType: 'Headset',
    cost: 189.99,
    minimumThreshold: 10,
    reorderAmount: 20,
    currentQuantity: 7,
    lastModifiedBy: 'jessica.wilson@company.com',
    lastModifiedDate: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    needsReorder: true,
  },
  {
    id: 7,
    itemNumber: 'WC-007',
    hardwareDescription: 'Logitech Brio 4K Webcam',
    hardwareType: 'Webcam',
    cost: 199.99,
    minimumThreshold: 5,
    reorderAmount: 10,
    currentQuantity: 14,
    lastModifiedBy: 'chris.martinez@company.com',
    lastModifiedDate: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    needsReorder: false,
  },
  {
    id: 8,
    itemNumber: 'DT-008',
    hardwareDescription: 'Dell OptiPlex 7090 Desktop',
    hardwareType: 'Desktop',
    cost: 1499.99,
    minimumThreshold: 5,
    reorderAmount: 10,
    currentQuantity: 3,
    lastModifiedBy: 'amanda.taylor@company.com',
    lastModifiedDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    needsReorder: true,
  },
];

const mockAuditHistory: AuditHistory[] = [
  {
    id: 1,
    itemId: 1,
    previousQuantity: 12,
    newQuantity: 8,
    changedBy: 'john.doe@company.com',
    changeDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    serviceNowTicketUrl: 'https://servicenow.company.com/ticket/INC0012345',
    item: mockInventoryItems[0],
  },
  {
    id: 2,
    itemId: 3,
    previousQuantity: 18,
    newQuantity: 12,
    changedBy: 'mike.johnson@company.com',
    changeDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    serviceNowTicketUrl: 'https://servicenow.company.com/ticket/INC0012346',
    item: mockInventoryItems[2],
  },
  {
    id: 3,
    itemId: 8,
    previousQuantity: 7,
    newQuantity: 3,
    changedBy: 'amanda.taylor@company.com',
    changeDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    serviceNowTicketUrl: 'https://servicenow.company.com/ticket/INC0012347',
    item: mockInventoryItems[7],
  },
  {
    id: 4,
    itemId: 5,
    previousQuantity: 15,
    newQuantity: 18,
    changedBy: 'alex.brown@company.com',
    changeDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    item: mockInventoryItems[4],
  },
  {
    id: 5,
    itemId: 6,
    previousQuantity: 11,
    newQuantity: 7,
    changedBy: 'jessica.wilson@company.com',
    changeDate: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    serviceNowTicketUrl: 'https://servicenow.company.com/ticket/INC0012348',
    item: mockInventoryItems[5],
  },
  {
    id: 6,
    itemId: 2,
    previousQuantity: 38,
    newQuantity: 45,
    changedBy: 'sarah.smith@company.com',
    changeDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    item: mockInventoryItems[1],
  },
  {
    id: 7,
    itemId: 7,
    previousQuantity: 10,
    newQuantity: 14,
    changedBy: 'chris.martinez@company.com',
    changeDate: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    item: mockInventoryItems[6],
  },
];

export const mockDashboardStats: DashboardStats = {
  totalItems: mockInventoryItems.length,
  lowStockCount: mockInventoryItems.filter(item => item.needsReorder).length,
  totalValue: mockInventoryItems.reduce((sum, item) => sum + (item.cost * item.currentQuantity), 0),
  recentChanges: mockAuditHistory,
};
