import type { InventoryItem, DashboardStats, AuditHistory, User } from '../types';

export const mockUser: User = {
  username: 'demo.user@company.com',
  roles: {
    isServiceDesk: true,
    isReadOnly: false,
    isAdmin: true,
  },
};

export const mockInventoryItems: InventoryItem[] = [
  // Hardware Items
  {
    id: 1,
    itemNumber: 'LT-001',
    assetType: 'Hardware',
    description: 'Dell Latitude 5420 Laptop',
    category: 'Laptop',
    cost: 1299.99,
    minimumThreshold: 10,
    reorderAmount: 20,
    currentQuantity: 8,
    lastModifiedBy: 'john.doe@company.com',
    lastModifiedDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    needsReorder: true,
    hardwareDescription: 'Dell Latitude 5420 Laptop',
    hardwareType: 'Laptop',
  },
  {
    id: 2,
    itemNumber: 'KB-002',
    assetType: 'Hardware',
    description: 'Logitech MX Keys Wireless Keyboard',
    category: 'Keyboard',
    cost: 99.99,
    minimumThreshold: 15,
    reorderAmount: 30,
    currentQuantity: 45,
    lastModifiedBy: 'sarah.smith@company.com',
    lastModifiedDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    needsReorder: false,
    hardwareDescription: 'Logitech MX Keys Wireless Keyboard',
    hardwareType: 'Keyboard',
  },
  {
    id: 3,
    itemNumber: 'MS-003',
    assetType: 'Hardware',
    description: 'Logitech MX Master 3 Mouse',
    category: 'Mouse',
    cost: 79.99,
    minimumThreshold: 20,
    reorderAmount: 40,
    currentQuantity: 12,
    lastModifiedBy: 'mike.johnson@company.com',
    lastModifiedDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    needsReorder: true,
    hardwareDescription: 'Logitech MX Master 3 Mouse',
    hardwareType: 'Mouse',
  },
  {
    id: 4,
    itemNumber: 'MON-004',
    assetType: 'Hardware',
    description: 'Dell 27" UltraSharp Monitor U2722DE',
    category: 'Monitor',
    cost: 549.99,
    minimumThreshold: 8,
    reorderAmount: 15,
    currentQuantity: 25,
    lastModifiedBy: 'emily.davis@company.com',
    lastModifiedDate: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    needsReorder: false,
    hardwareDescription: 'Dell 27" UltraSharp Monitor U2722DE',
    hardwareType: 'Monitor',
  },
  {
    id: 5,
    itemNumber: 'DK-005',
    assetType: 'Hardware',
    description: 'Dell Docking Station WD19TB',
    category: 'Docking Station',
    cost: 299.99,
    minimumThreshold: 12,
    reorderAmount: 25,
    currentQuantity: 18,
    lastModifiedBy: 'alex.brown@company.com',
    lastModifiedDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    needsReorder: false,
    hardwareDescription: 'Dell Docking Station WD19TB',
    hardwareType: 'Docking Station',
  },
  {
    id: 6,
    itemNumber: 'HD-006',
    assetType: 'Hardware',
    description: 'Jabra Evolve2 65 Headset',
    category: 'Headset',
    cost: 189.99,
    minimumThreshold: 10,
    reorderAmount: 20,
    currentQuantity: 7,
    lastModifiedBy: 'jessica.wilson@company.com',
    lastModifiedDate: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    needsReorder: true,
    hardwareDescription: 'Jabra Evolve2 65 Headset',
    hardwareType: 'Headset',
  },
  {
    id: 7,
    itemNumber: 'WC-007',
    assetType: 'Hardware',
    description: 'Logitech Brio 4K Webcam',
    category: 'Webcam',
    cost: 199.99,
    minimumThreshold: 5,
    reorderAmount: 10,
    currentQuantity: 14,
    lastModifiedBy: 'chris.martinez@company.com',
    lastModifiedDate: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    needsReorder: false,
    hardwareDescription: 'Logitech Brio 4K Webcam',
    hardwareType: 'Webcam',
  },
  {
    id: 8,
    itemNumber: 'DT-008',
    assetType: 'Hardware',
    description: 'Dell OptiPlex 7090 Desktop',
    category: 'Desktop',
    cost: 1499.99,
    minimumThreshold: 5,
    reorderAmount: 10,
    currentQuantity: 3,
    lastModifiedBy: 'amanda.taylor@company.com',
    lastModifiedDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    needsReorder: true,
    hardwareDescription: 'Dell OptiPlex 7090 Desktop',
    hardwareType: 'Desktop',
  },

  // Software Items
  {
    id: 9,
    itemNumber: 'SW-001',
    assetType: 'Software',
    description: 'Zoom Enterprise License',
    category: 'Zoom',
    cost: 19.99,
    minimumThreshold: 100,
    reorderAmount: 200,
    currentQuantity: 320,
    lastModifiedBy: 'admin@company.com',
    lastModifiedDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    needsReorder: false,
  },
  {
    id: 10,
    itemNumber: 'SW-002',
    assetType: 'Software',
    description: 'Adobe Acrobat Pro DC License',
    category: 'Adobe Pro',
    cost: 54.99,
    minimumThreshold: 20,
    reorderAmount: 30,
    currentQuantity: 15,
    lastModifiedBy: 'admin@company.com',
    lastModifiedDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    needsReorder: true,
  },
  {
    id: 11,
    itemNumber: 'SW-003',
    assetType: 'Software',
    description: 'Microsoft Visio Professional License',
    category: 'Visio',
    cost: 15.00,
    minimumThreshold: 25,
    reorderAmount: 50,
    currentQuantity: 42,
    lastModifiedBy: 'admin@company.com',
    lastModifiedDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    needsReorder: false,
  },
  {
    id: 12,
    itemNumber: 'SW-004',
    assetType: 'Software',
    description: 'ServiceNow IT Service Management Utilities',
    category: 'ServiceNow Utilities',
    cost: 125.00,
    minimumThreshold: 30,
    reorderAmount: 50,
    currentQuantity: 85,
    lastModifiedBy: 'admin@company.com',
    lastModifiedDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    needsReorder: false,
  },
  {
    id: 13,
    itemNumber: 'SW-005',
    assetType: 'Software',
    description: 'Laserfiche Enterprise License',
    category: 'Laserfiche',
    cost: 95.00,
    minimumThreshold: 15,
    reorderAmount: 25,
    currentQuantity: 8,
    lastModifiedBy: 'admin@company.com',
    lastModifiedDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    needsReorder: true,
  },
  {
    id: 14,
    itemNumber: 'SW-006',
    assetType: 'Software',
    description: 'Microsoft Project Professional License',
    category: 'Project',
    cost: 30.00,
    minimumThreshold: 20,
    reorderAmount: 40,
    currentQuantity: 35,
    lastModifiedBy: 'admin@company.com',
    lastModifiedDate: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    needsReorder: false,
  },
  {
    id: 15,
    itemNumber: 'SW-007',
    assetType: 'Software',
    description: 'LinkedIn Learning Enterprise License',
    category: 'LinkedIn',
    cost: 39.99,
    minimumThreshold: 50,
    reorderAmount: 100,
    currentQuantity: 45,
    lastModifiedBy: 'admin@company.com',
    lastModifiedDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    needsReorder: true,
  },
];

const mockAuditHistory: AuditHistory[] = [
  {
    id: 1,
    itemId: 1,
    previousQuantity: 12,
    newQuantity: 8,
    changedBy: 'john.doe@company.com',
    changeDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    serviceNowTicketUrl: 'https://servicenow.company.com/ticket/INC0012345',
    item: mockInventoryItems[0],
  },
  {
    id: 2,
    itemId: 3,
    previousQuantity: 18,
    newQuantity: 12,
    changedBy: 'mike.johnson@company.com',
    changeDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    serviceNowTicketUrl: 'https://servicenow.company.com/ticket/INC0012346',
    item: mockInventoryItems[2],
  },
  {
    id: 3,
    itemId: 8,
    previousQuantity: 7,
    newQuantity: 3,
    changedBy: 'amanda.taylor@company.com',
    changeDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    serviceNowTicketUrl: 'https://servicenow.company.com/ticket/INC0012347',
    item: mockInventoryItems[7],
  },
  {
    id: 4,
    itemId: 5,
    previousQuantity: 15,
    newQuantity: 18,
    changedBy: 'alex.brown@company.com',
    changeDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    item: mockInventoryItems[4],
  },
  {
    id: 5,
    itemId: 6,
    previousQuantity: 11,
    newQuantity: 7,
    changedBy: 'jessica.wilson@company.com',
    changeDate: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    serviceNowTicketUrl: 'https://servicenow.company.com/ticket/INC0012348',
    item: mockInventoryItems[5],
  },
  {
    id: 6,
    itemId: 2,
    previousQuantity: 38,
    newQuantity: 45,
    changedBy: 'sarah.smith@company.com',
    changeDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    item: mockInventoryItems[1],
  },
  {
    id: 7,
    itemId: 7,
    previousQuantity: 10,
    newQuantity: 14,
    changedBy: 'chris.martinez@company.com',
    changeDate: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    item: mockInventoryItems[6],
  },
  {
    id: 8,
    itemId: 10,
    previousQuantity: 25,
    newQuantity: 15,
    changedBy: 'admin@company.com',
    changeDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    item: mockInventoryItems[9],
  },
  {
    id: 9,
    itemId: 13,
    previousQuantity: 12,
    newQuantity: 8,
    changedBy: 'admin@company.com',
    changeDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    item: mockInventoryItems[12],
  },
];

const mockAuditHistory2: AuditHistory = {
  id: 10,
  itemId: 15,
  previousQuantity: 55,
  newQuantity: 45,
  changedBy: 'admin@company.com',
  changeDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  item: mockInventoryItems[14],
};

export const mockDashboardStats: DashboardStats = {
  totalItems: mockInventoryItems.length,
  lowStockCount: mockInventoryItems.filter(item => item.needsReorder).length,
  totalValue: mockInventoryItems.reduce((sum, item) => sum + (item.cost * item.currentQuantity), 0),
  recentChanges: [...mockAuditHistory, mockAuditHistory2],
};
